"""Add default to Order_status

Revision ID: 37562ae0635c
Revises: 6bd7cb595ae6
Create Date: 2024-12-13 19:36:31.458854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37562ae0635c'
down_revision = '6bd7cb595ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('date_ordered',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('date_ordered',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
